export const SERVICES = [
  {
    id: 1,
    num: "01",
    icon: "⛰",
    title: "Topographical Survey",
    image: "https://plus.unsplash.com/premium_photo-1713165737075-20aebf07a82f",
    sub: "Urban Mapping & Planning",
    category: "Urban Planning",
    desc: "High-accuracy drone surveys delivering detailed topographic maps, LULC classification, 3D mesh models, DEM, DSM, and watershed analysis for urban infrastructure planning.",
    process: ["UAV Flight Planning", "Image Acquisition", "Point Cloud Processing", "GIS Feature Extraction"],
    deliverables: ["Topographical Maps", "LULC Maps", "3D Mesh Model", "DEM / DSM", "Watershed Analysis", "Mobile App Output"],
  },
  {
    id: 2,
    num: "02",
    icon: "🏢",
    title: "3D Reality Model",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200",
    sub: "Digital Twin & Property Tax",
    category: "Urban Planning",
    desc: "Photorealistic 3D digital twins enabling property tax evasion detection, city planning simulation and infrastructure asset management at scale.",
    process: ["Oblique Image Capture", "Dense Point Cloud", "3D Mesh Generation", "Database Integration"],
    deliverables: ["3D City Model", "Property Database", "Tax Evasion Reports", "Digital Twin Platform"],
  },
  {
    id: 3,
    num: "03",
    icon: "📍",
    title: "Door to Door Survey",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1200",
    sub: "Geo-Database Creation",
    category: "Urban Planning",
    desc: "Comprehensive field surveys integrated with drone mapping to create precise geo-databases covering utilities, building assets, and municipal planning datasets.",
    process: ["Field Data Collection", "Drone Ortho-mapping", "Data Integration", "Database Creation"],
    deliverables: ["Geo-Database", "Utility Network Maps", "3D Mesh Model", "DSM Outputs", "Mobile Field App"],
  },
  {
    id: 4,
    num: "04",
    icon: "🔩",
    title: "Underground Utility Mapping",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200",
    sub: "Sewerage & Drainage",
    category: "Infrastructure",
    desc: "GPR-based mapping of underground sewerage, drainage and utility networks overlaid on drone ortho-imagery for critical infrastructure planning and maintenance.",
    process: ["GPR Acquisition", "Signal Processing", "Feature Identification", "GIS Integration"],
    deliverables: ["Utility Network Maps", "Pipeline GIS Layers", "Asset Register", "Infrastructure Reports"],
  },
  {
    id: 5,
    num: "05",
    icon: "💧",
    title: "Water Body Mapping",
    image: "https://images.unsplash.com/photo-1439405326854-014607f694d7?w=1200",
    sub: "Restoration Projects",
    category: "Water & Environment",
    desc: "Comprehensive lake, reservoir, and canal mapping for ecological restoration capturing bed levels, bund levels, inlet/outlet structures, and full hydrological data.",
    process: ["UAV & Bathymetric Survey", "Ortho-mosaic Generation", "3D Point Cloud", "Hydrological Analysis"],
    deliverables: ["Lake Topo Map", "Canal Cross-sections", "DEM", "Spot Levels", "Watershed Map", "3D Dense Point Cloud"],
  },
  {
    id: 6,
    num: "06",
    icon: "🌊",
    title: "Flood Mapping",
    image: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=1200",
    sub: "Watershed Management",
    category: "Water & Environment",
    desc: "High-resolution flood zone mapping and watershed modelling using drone DEM data for disaster risk management, urban drainage design, and climate resilience planning.",
    process: ["High-res Drone Survey", "Image Alignment", "Elevation Modelling", "Flood Simulation"],
    deliverables: ["Flood Zone Maps", "Watershed Models", "DEM Products", "Contour Maps", "Risk Reports"],
  },
  {
    id: 7,
    num: "07",
    icon: "⛏",
    title: "Volumetric Analysis",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200",
    sub: "Mines & Stockpiles",
    category: "Mining & Volumetric",
    desc: "Rapid, accurate volumetric estimation of mining operations, quarries and stockpiles using drone photogrammetry with GCP control for compliance, billing, and planning.",
    process: ["Drone Survey", "GCP Placement", "Point Cloud Processing", "Volume Calculation"],
    deliverables: ["Volume Reports", "Contour Maps", "Cross-section Profiles", "Topographical Maps"],
  },
  {
    id: 8,
    num: "08",
    icon: "🗺",
    title: "Cadastral Georeferencing",
    image: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1200",
    sub: "Infrastructure & Roadways",
    category: "Infrastructure",
    desc: "Digitizing and precision-georeferencing of FMB/cadastral maps overlaid on drone ortho-imagery for accurate land parcel identification and right-of-way surveys.",
    process: ["Historical Map Collection", "Drone Ortho-mosaic", "Georeferencing", "Cadastral Digitization"],
    deliverables: ["FMB Alignment Maps", "Cadastral GIS Layers", "DEM", "LiDAR DSM"],
  },
  {
    id: 9,
    num: "09",
    icon: "🎥",
    title: "Project Monitoring",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200",
    sub: "Roads & Railways",
    category: "Monitoring",
    desc: "Scheduled drone-based progress monitoring and 4K videography of road and railway infrastructure projects for documentation, change detection, and quality reporting.",
    process: ["Scheduled Flight Ops", "Video & Image Capture", "Change Detection", "Report Delivery"],
    deliverables: ["Progress Videos", "Orthomosaics", "Change Detection Maps", "Monitoring Reports"],
  },
];

export const SERVICE_TABS = [
  "All Services",
  "Urban Planning",
  "Water & Environment",
  "Infrastructure",
  "Mining & Volumetric",
  "Monitoring",
];

export const CATEGORY_META = {
  "Urban Planning": {
    tagline: "Precision mapping for cities of tomorrow",
    heroColor: "#0D6E6E",
    heroAccent: "#2563EB",
    bgImage: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1600",
  },
  "Water & Environment": {
    tagline: "Hydrological intelligence from above",
    heroColor: "#0369A1",
    heroAccent: "#0D6E6E",
    bgImage: "https://images.unsplash.com/photo-1439405326854-014607f694d7?w=1600",
  },
  Infrastructure: {
    tagline: "Underground clarity, overground confidence",
    heroColor: "#374151",
    heroAccent: "#2563EB",
    bgImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600",
  },
  "Mining & Volumetric": {
    tagline: "Volume calculations you can stake claims on",
    heroColor: "#92400E",
    heroAccent: "#D97706",
    bgImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1600",
  },
  Monitoring: {
    tagline: "Every phase documented, every change tracked",
    heroColor: "#1E3A5F",
    heroAccent: "#2563EB",
    bgImage: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1600",
  },
};